<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:extns="http://www.example.org/schema/1667366368702" xmlns:tns="http://www.example.org/wsdl/1667366368602" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="SalaryProcessReference" targetNamespace="http://www.example.org/wsdl/1667366368602" xmlns:xsd1="http://www.example.org/Insert_Employee_Data">
  <wsdl:import location="../Schemas/SalaryProcessReferenceSchema.xsd" namespace="http://www.example.org/schema/1667366368702"/>
  <wsdl:types>
  	<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  		<xsd:import
  			namespace="http://www.example.org/Insert_Employee_Data"
  			schemaLocation="../Schemas/Insert_Employee_Data.xsd">
  		</xsd:import></xsd:schema></wsdl:types>
  <wsdl:message name="operationRequest">
    <wsdl:part element="xsd1:InsertEmpSalary" name="parameters"/>
  </wsdl:message>
  <wsdl:message name="operationResponse">
    <wsdl:part element="xsd1:InsertDataResposnse" name="parameters"/>
  </wsdl:message>
  <wsdl:portType name="SalaryProcessReference">
    <wsdl:operation name="operation">
      <wsdl:input message="tns:operationRequest" name="operationInput"/>
      <wsdl:output message="tns:operationResponse" name="operationOutput"/>
    </wsdl:operation>
  </wsdl:portType>
</wsdl:definitions>
